name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  syncfusion_flutter_datepicker: ^19.4.56
  flutter_beautiful_popup: ^1.7.0
