name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

assets:
  - env.env

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  google_maps_flutter: ^2.1.2
  flutter_config: ^2.0.0
  location: ^4.3.0
  syncfusion_flutter_datepicker: ^19.4.56
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
